version: '3.8'  # Update to a supported version, '3' is obsolete

services:
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - vin_env=1
      - DATABASE_ENGINE=django.db.backends.mysql
      - DATABASE_NAME=vin
      - DATABASE_USER=saitreddy
      - DATABASE_PASSWORD=sai
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - media_volume:/app/media/
      - static_volume:/app/static/
    depends_on:
      - db
      - redis
      - celery
      - celery-beat

  celery:
    build: .
    command: celery -A vin worker -l info
    volumes:
      - media_volume:/app/media/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_ENGINE=django.db.backends.mysql
      - DATABASE_NAME=vin
      - DATABASE_USER=saitreddy
      - DATABASE_PASSWORD=sai
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A vin beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - media_volume:/app/media/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_ENGINE=django.db.backends.mysql
      - DATABASE_NAME=vin
      - DATABASE_USER=saitreddy
      - DATABASE_PASSWORD=sai
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Map host port 6379 to container port 6379

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=sai
      - MYSQL_DATABASE=vin
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql
    
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media_volume:/app/media/
      - static_volume:/app/static/
    depends_on:
      - django

volumes:
  media_volume:
  mysql_data:
  static_volume:
