# Generated by Django 5.1.1 on 2024-09-09 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='MachineParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=200)),
                ('color_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MachineParameters',
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100, unique=True, verbose_name='Plant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'Plant',
            },
        ),
        migrations.CreateModel(
            name='StoppageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Stoppage',
            },
        ),
        migrations.CreateModel(
            name='DownTimeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_stop_time', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_stop_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('gate', models.CharField(blank=True, max_length=100, null=True)),
                ('gate_open_duration', models.CharField(max_length=100)),
                ('area_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('areas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.areas')),
            ],
            options={
                'db_table': 'DownTimeAnalysis',
            },
        ),
        migrations.CreateModel(
            name='MachineTemperatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontal', models.CharField(blank=True, max_length=100, null=True)),
                ('teeth', models.BooleanField(blank=True, default=False, null=True)),
                ('coder', models.BooleanField(blank=True, default=False, null=True)),
                ('vertical', models.CharField(blank=True, max_length=1000, null=True)),
                ('recorded_date_time', models.CharField(blank=True, max_length=200, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
            ],
            options={
                'db_table': 'MachineTemperatures',
            },
        ),
        migrations.AddField(
            model_name='machines',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.plant'),
        ),
        migrations.CreateModel(
            name='MachineParametersGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_count', models.CharField(blank=True, max_length=200, null=True)),
                ('recorded_date_time', models.CharField(blank=True, max_length=200, null=True)),
                ('machine_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.machineparameters')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
            ],
            options={
                'db_table': 'MachineParametersGraph',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.AddField(
            model_name='areas',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.plant'),
        ),
        migrations.CreateModel(
            name='AreaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField(blank=True, null=True)),
                ('recorded_date_time', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.areas')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
            ],
            options={
                'db_table': 'AreaNotification',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.plant')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='LiquidPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('recorded_date_time', models.CharField(blank=True, max_length=200, null=True)),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.areas')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('machines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.products')),
            ],
            options={
                'db_table': 'LiquidPlant',
            },
        ),
        migrations.CreateModel(
            name='RootCauseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rca1', models.CharField(blank=True, max_length=255, null=True)),
                ('rca2', models.CharField(blank=True, max_length=255, null=True)),
                ('rca3', models.CharField(blank=True, max_length=255, null=True)),
                ('rca4', models.CharField(blank=True, max_length=255, null=True)),
                ('rca5', models.CharField(blank=True, max_length=255, null=True)),
                ('rca6', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.areas')),
            ],
            options={
                'db_table': 'Root Cause Analysis',
            },
        ),
        migrations.CreateModel(
            name='ShampooPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('recorded_date_time', models.CharField(blank=True, max_length=200, null=True)),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.areas')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('machines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.products')),
            ],
            options={
                'db_table': 'ShampooPlant',
            },
        ),
        migrations.CreateModel(
            name='Khamgaon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
                ('recorded_date_time', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('areas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.areas')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('machines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.products')),
                ('type_of_stoppage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.stoppagetype')),
            ],
            options={
                'db_table': 'Khamgaon',
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_status', models.BooleanField(default=True, verbose_name='System Status')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
            ],
            options={
                'db_table': 'SystemStatus',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date_time', models.CharField(max_length=255)),
                ('total_duration', models.FloatField(default=0)),
                ('areas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.areas')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('machines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.products')),
                ('type_of_stoppage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.stoppagetype')),
            ],
            options={
                'db_table': 'Dashboard',
                'indexes': [models.Index(fields=['recorded_date_time'], name='Dashboard_recorde_603b18_idx')],
            },
        ),
    ]
