# Generated by Django 4.2.13 on 2024-07-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefectNotification',
            new_name='AreaNotification',
        ),
        migrations.RenameModel(
            old_name='Defects',
            new_name='Areas',
        ),
        migrations.AlterModelTable(
            name='areanotification',
            table='AreaNotification',
        ),
        migrations.AlterModelTable(
            name='areas',
            table='Areas',
        ),
    ]
