# Generated by Django 4.2.13 on 2024-07-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_systemstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date_time', models.CharField(max_length=255)),
                ('count', models.BigIntegerField(default=0)),
                ('defects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.defects')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.department')),
                ('machines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.products')),
            ],
            options={
                'db_table': 'Dashboard',
            },
        ),
    ]
