# Generated by Django 4.2.13 on 2024-07-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_defectnotification_areanotification_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NMBDashboard',
            new_name='Khamgaon',
        ),
        migrations.AlterModelTable(
            name='khamgaon',
            table='Khamgaon',
        ),
    ]
