# Generated by Django 4.2.13 on 2024-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboard'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['plant', 'recorded_date_time'], name='Dashboard_plant_i_76f21b_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['defects'], name='Dashboard_defects_3a0653_idx'),
        ),
    ]
