# Generated by Django 4.2.13 on 2024-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_nmbdashboard_khamgaon_alter_khamgaon_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='khamgaon',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
