# Generated by Django 4.2.13 on 2024-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_dashboard_plant_i_76f21b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dashboard',
            name='Dashboard_plant_i_76f21b_idx',
        ),
        migrations.RemoveIndex(
            model_name='dashboard',
            name='Dashboard_defects_3a0653_idx',
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['product', 'recorded_date_time'], name='Dashboard_product_6f61a7_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['machines'], name='Dashboard_machine_131da9_idx'),
        ),
    ]
