# Generated by Django 4.2.13 on 2024-07-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_khamgaon_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areanotification',
            old_name='defect',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='defects',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='khamgaon',
            old_name='defects',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='liquidplant',
            old_name='defects',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='rootcauseanalysis',
            old_name='defect',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='shampooplant',
            old_name='defects',
            new_name='areas',
        ),
    ]
