# Generated by Django 4.2.13 on 2024-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_defect_areanotification_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='count',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_duration',
            field=models.FloatField(default=0),
        ),
    ]
