# Generated by Django 4.2.13 on 2024-07-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_dashboard_dashboard_plant_i_76f21b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dashboard',
            name='Dashboard_product_6f61a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='dashboard',
            name='Dashboard_machine_131da9_idx',
        ),
    ]
