# Generated by Django 4.2.13 on 2024-07-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_dashboard_dashboard_product_6f61a7_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
