# Generated by Django 4.2.13 on 2024-07-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_khamgaon_areas_alter_khamgaon_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khamgaon',
            name='department',
        ),
        migrations.RemoveField(
            model_name='khamgaon',
            name='product',
        ),
    ]
