# Generated by Django 4.2.13 on 2024-07-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_dashboard'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['recorded_date_time'], name='Dashboard_recorde_603b18_idx'),
        ),
    ]
