# Generated by Django 4.2.13 on 2024-07-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_khamgaon_department_remove_khamgaon_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='khamgaon',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
        ),
        migrations.AddField(
            model_name='khamgaon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.products'),
        ),
    ]
