# Generated by Django 4.2.13 on 2024-07-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_khamgaon_department_khamgaon_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.areas'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='machines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.machines'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.products'),
        ),
    ]
