# Generated by Django 4.2.13 on 2024-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_dashboard_areas_alter_dashboard_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='color_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
